site_name: Randy Rowland
site_description: Testing out MkDocs tools. 
site_author: Randy Rowland
repo_url: https://github.com/rowland007/rowland007.github.io/
strict: true
theme: windmill

markdown_extensions:
  - smarty
  - attr_list
  - admonition
  - toc:
      permalink: True
plugins:
  - search:
      lang: en

nav:
  - About: index.md
  - Security:
    - GPG: security/gpg.md
    - Syncthing: security/syncthing.md
    - Signing Software: security/signing-software.md
    